### ISSUE TITLE
Package sufix

### ISSUE THREAD

**Issue by vonmecheln** [Provizanta/ansible-role-latex#1]
https://github.com/Provizanta/ansible-role-latex/blob/96fe1d95b680f76aac641ac5183dfb1028b511cd/tasks/main.yml#L23

< TASK [teebor_choka.latex : establish extensions] >
 --------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'texlive-extra-utils**texlive-**' is available"}

![Captura de tela de 2019-07-24 12-03-33](https://user-images.githubusercontent.com/318178/61804880-1b747100-ae0b-11e9-9271-3097f0e94d15.png)

**Comment by Teebor-Choka** [comment]
Hi, thank you for the raised issue.

The `extensions` variable originally took a list of extensions in the form: original name without the `texlive-` prefix. The prefix would then be appended by the role. I now see that this is confusing for a user attempting to use the role, so your proposed fix is a viable solution.

**Comment by Teebor-Choka** [comment]
Closed by PR#1 and test fix.

Thanks, @vonmecheln
